In [4]:
import tensorflow as tf
print(tf.__version__)

1.15.0


In [5]:
a = tf.constant(1234)
b = tf.constant(5000)

add_op = a+b

sess = tf.Session()
res = sess.run(add_op)
print(res)

6234


In [6]:
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(4)

calc1_op = a+b*c
calc2_op = (a+b)*c

res1 = sess.run(calc1_op)
print(res1)
res2 = sess.run(calc2_op)
print(res2)

14
20


In [10]:
a = tf.constant(100)
b = tf.constant(50) #상수 정의

add_op = a+b

v = tf.Variable(0) #변수 v 선언

let_op = tf.assign(v, add_op) #변수 v에 add_op의 결과 대입

sess = tf.Session()
sess.run(tf.global_variables_initializer()) #변수 초기화(메모리에 생성)

sess.run(let_op) #계산식 실행
print(sess.run(v))

150


In [13]:
#placeholder - 정수 자료형 n개를 가진 배열 tf.placeholder(tf.int32, [n])
a = tf.placeholder(tf.int32, [4])
b = tf.constant(2)
x2_op = a*b

sess = tf.Session()

r1 = sess.run(x2_op, feed_dict = {a:[1, 2, 3, 4]})
print(r1)
r2 = sess.run(x2_op, feed_dict = {a:[10, 20, 10, 20]})
print(r2)

[2 4 6 8]
[20 40 20 40]


In [14]:
a = tf.placeholder(tf.int32, [None]) #None으로 지정할 시 입력한 dict 길이만큼 알아서 출력
b = tf.constant(10)
x10_op = a*b

r1 = sess.run(x10_op, feed_dict={a:[1, 2, 3, 4, 5]})
print(r1)
r2 = sess.run(x10_op, feed_dict={a:[10, 20]})
print(r2)

[10 20 30 40 50]
[100 200]


In [16]:
#tensorboard 
a = tf.constant(20, name = 'a')
b = tf.constant(30, name= 'b')
mul_op = a*b

sess = tf.Session()
tw = tf.summary.FileWriter("log_dir", graph=sess.graph)
print(sess.run(mul_op))

600


In [18]:
#Least square
import numpy as np

x = [2, 4, 6, 8]
y = [81, 93, 91, 97]

mx = np.mean(x)
my = np.mean(y)

divisor = sum([(mx-i)**2 for i in x])

def top(x, mx, y, my):
    d = 0
    for i in range(len(x)):
        d += (x[i]-mx)*(y[i]-my)
    return d

In [27]:
divided = top(x, mx, y, my)
a = divided/divisor
print(a)

2.3


In [28]:
b = my-mx*a
print(b)

79.0


In [31]:
#RMSE
#임의의 기울기와 절편
ab = [3, 76]
data = [[2, 81], [4, 93], [6, 91], [8,97]]

x = [i[0] for i in data]
y = [i[1] for i in data]

#임의의 기울기와 저편의 모델로부터 예측값 반환 함수
def predict(x):
    return ab[0]*x+ab[1]

#RMSE 반환 함수
def rmse(p, a): #p = 예측, a = 실제
    return np.sqrt(((p-a)**2).mean())

predict_result = []

for i in range(len(x)):
    predict_result.append(predict(x[i]))
    print('time = %.f, score = %.f, predict_score = %.f' %(x[i], y[i], predict_result[i]))


#RMSE 반환 함수를 이용하여 최종값 구하기
def rmse_val(predict_result, y):
    return rmse(np.array(predict_result), np.array(y))

print("rmse_result:"+str(rmse_val(predict_result, y)))

time = 2, score = 81, predict_score = 82
time = 4, score = 93, predict_score = 88
time = 6, score = 91, predict_score = 94
time = 8, score = 97, predict_score = 100
rmse_result:3.3166247903554


In [41]:
#gradient decent(경사하강법) 학습률 지정
import tensorflow as tf

data = [[2, 81], [4, 93], [6, 91], [8,97]]

x_data = [i[0] for i in data]
y_data = [i[1] for i in data]

#기울기, y절편 임의 지정(변수)
a = tf.Variable(tf.random_uniform([1], 0, 10, dtype=tf.float64, seed=0))
b = tf.Variable(tf.random_uniform([1], 0, 100, dtype=tf.float64, seed=0))
y = a*x_data+b

#오차계산(RMSE)

rmse = tf.sqrt(tf.reduce_mean(tf.square(y-y_data)))

#학습률

learning_rate = 0.1

#오차 최소
gradient_descent = tf.train.GradientDescentOptimizer(learning_rate).minimize(rmse)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(gradient_descent)
        if step % 100 == 0:
            print("Epoch: %.f, RMSE : %.4f, 기울기: %.4f, y절편: %.4f"
                  %(step, sess.run(rmse), sess.run(a), sess.run(b)))

#Epoch, 입력값에 대해 몇번 반복하였는지를 나타내는 용어

Epoch: 0, RMSE : 30.2139, 기울기: 7.5235, y절편: 80.5984
Epoch: 100, RMSE : 2.8860, 기울기: 2.2299, y절편: 79.4181
Epoch: 200, RMSE : 2.8826, 기울기: 2.2601, y절편: 79.2379
Epoch: 300, RMSE : 2.8815, 기울기: 2.2773, y절편: 79.1353
Epoch: 400, RMSE : 2.8811, 기울기: 2.2871, y절편: 79.0770
Epoch: 500, RMSE : 2.8810, 기울기: 2.2927, y절편: 79.0438
Epoch: 600, RMSE : 2.8810, 기울기: 2.2958, y절편: 79.0249
Epoch: 700, RMSE : 2.8810, 기울기: 2.2976, y절편: 79.0142
Epoch: 800, RMSE : 2.8810, 기울기: 2.2987, y절편: 79.0081
Epoch: 900, RMSE : 2.8810, 기울기: 2.2992, y절편: 79.0046
Epoch: 1000, RMSE : 2.8810, 기울기: 2.2996, y절편: 79.0026
Epoch: 1100, RMSE : 2.8810, 기울기: 2.2998, y절편: 79.0015
Epoch: 1200, RMSE : 2.8810, 기울기: 2.2999, y절편: 79.0008
Epoch: 1300, RMSE : 2.8810, 기울기: 2.2999, y절편: 79.0005
Epoch: 1400, RMSE : 2.8810, 기울기: 2.3000, y절편: 79.0003
Epoch: 1500, RMSE : 2.8810, 기울기: 2.3000, y절편: 79.0002
Epoch: 1600, RMSE : 2.8810, 기울기: 2.3000, y절편: 79.0001
Epoch: 1700, RMSE : 2.8810, 기울기: 2.3000, y절편: 79.0001
Epoch: 1800, RMSE : 2.8810, 기울기: 2.3000

In [43]:
#gradient decent(경사하강법) 학습률 지정 다중선형회귀
import tensorflow as tf

data = [[2, 81, 0], [4, 93, 4], [6, 91, 2], [8,97, 3]]

x1_data = [i[0] for i in data]
x2_data = [i[2] for i in data]
y_data = [i[1] for i in data]


#기울기, y절편 임의 지정(변수)
a1 = tf.Variable(tf.random_uniform([1], 0, 10, dtype=tf.float64, seed=0))
a2 = tf.Variable(tf.random_uniform([1], 0, 10, dtype=tf.float64, seed=0))
b = tf.Variable(tf.random_uniform([1], 0, 100, dtype=tf.float64, seed=0))
y = a1*x1_data+ a2*x2_data + b

#오차계산(RMSE)

rmse = tf.sqrt(tf.reduce_mean(tf.square(y-y_data)))

#학습률

learning_rate = 0.1

#오차 최소
gradient_descent = tf.train.GradientDescentOptimizer(learning_rate).minimize(rmse)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(gradient_descent)
        if step % 100 == 0:
            print("Epoch: %.f, RMSE : %.4f, 기울기1: %.4f, 기울기2: %.4f y절편: %.4f"
                  %(step, sess.run(rmse), sess.run(a1), sess.run(a2), sess.run(b)))

#Epoch, 입력값에 대해 몇번 반복하였는지를 나타내는 용어

Epoch: 0, RMSE : 49.1842, 기울기1: 7.5270, 기울기2: 7.8160 y절편: 80.5980
Epoch: 100, RMSE : 1.8368, 기울기1: 1.1306, 기울기2: 2.1316 y절편: 78.5119
Epoch: 200, RMSE : 1.8370, 기울기1: 1.1879, 기울기2: 2.1487 y절편: 78.1057
Epoch: 300, RMSE : 1.8370, 기울기1: 1.2122, 기울기2: 2.1571 y절편: 77.9352
Epoch: 400, RMSE : 1.8370, 기울기1: 1.2226, 기울기2: 2.1607 y절편: 77.8636
Epoch: 500, RMSE : 1.8370, 기울기1: 1.2269, 기울기2: 2.1622 y절편: 77.8335
Epoch: 600, RMSE : 1.8370, 기울기1: 1.2288, 기울기2: 2.1628 y절편: 77.8208
Epoch: 700, RMSE : 1.8370, 기울기1: 1.2295, 기울기2: 2.1631 y절편: 77.8155
Epoch: 800, RMSE : 1.8370, 기울기1: 1.2299, 기울기2: 2.1632 y절편: 77.8133
Epoch: 900, RMSE : 1.8370, 기울기1: 1.2300, 기울기2: 2.1632 y절편: 77.8124
Epoch: 1000, RMSE : 1.8370, 기울기1: 1.2301, 기울기2: 2.1633 y절편: 77.8120
Epoch: 1100, RMSE : 1.8370, 기울기1: 1.2301, 기울기2: 2.1633 y절편: 77.8118
Epoch: 1200, RMSE : 1.8370, 기울기1: 1.2301, 기울기2: 2.1633 y절편: 77.8117
Epoch: 1300, RMSE : 1.8370, 기울기1: 1.2301, 기울기2: 2.1633 y절편: 77.8117
Epoch: 1400, RMSE : 1.8370, 기울기1: 1.2301, 기울기2: 2.1633 y절편:

In [54]:
#logistic regression

import tensorflow as tf
import numpy as np

data = [[2, 0], [4, 0], [6, 0], [8, 1], [10, 1], [12, 1], [14, 1]]

x_data = [i[0] for i in data]
y_data = [i[1] for i in data]

a = tf.Variable(tf.random_normal([1], dtype=tf.float64, seed=0))
b = tf.Variable(tf.random_normal([1], dtype=tf.float64, seed=0))

#시그모이드 함수 방정식의 정의
y = 1/(1+np.e**(a*x_data+b))

loss = -tf.reduce_mean(np.array(y_data)*tf.log(y)+(1-np.array(y_data))*tf.log(1-y))

learning_rate = 0.5

gradient_descent = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(6001):
        sess.run(gradient_descent)
        if step % 1000 == 0:
            print("Epoch: %.f, loss : %.4f, 기울기: %.4f, y절편: %.4f"
                  %(step, sess.run(loss), sess.run(a), sess.run(b)))


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch: 0, loss : 1.2676, 기울기: 0.1849, y절편: -0.4334
Epoch: 1000, loss : 0.0557, 기울기: -1.6009, y절편: 11.0208
Epoch: 2000, loss : 0.0361, 기울기: -2.0366, y절편: 14.0909
Epoch: 3000, loss : 0.0269, 기울기: -2.3380, y절편: 16.2087
Epoch: 4000, loss : 0.0214, 기울기: -2.5708, y절편: 17.8417
Epoch: 5000, loss : 0.0178, 기울기: -2.7607, y절편: 19.1734
Epoch: 6000, loss : 0.0152, 기울기: -2.9211, y절편: 20.2982


In [67]:
#다중입력값 logistic regression

x_data = np.array([[2, 3], [4, 3], [6, 4], [8, 6], [10, 7], [12, 8], [14, 7]])
y_data = np.array([0, 0, 0, 1, 1, 1, 1]).reshape(7, 1)

#입력값을 placeholder에 저장
X = tf.placeholder(tf.float64, shape=[None, 2])
Y = tf.placeholder(tf.float64, shape=[None, 1])

#실행할 때마다 동일한 출력(결과)를 얻기 위한 값 설정
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

a = tf.Variable(tf.random_uniform([2, 1], dtype=tf.float64))
#[2, 1]들어오는 값은 2, 나가는 값은 1
b = tf.Variable(tf.random_uniform([1], dtype=tf.float64))

y = tf.sigmoid(tf.matmul(X, a) + b)

loss = -tf.reduce_mean(Y*tf.log(y)+(1-Y)*tf.log(1-y))

learning_rate = 0.1

gradient_descent = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

predicted = tf.cast(y >0.5, dtype=tf.float64)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float64))

#tf.cast() 함수는 형변환(cast) 수행 > 부동소수점형(실수)를 정수형으로 변환할때 소수점 이하 버림 bool(논리) 자료형 으로 변환할때 True = 1, False = 0 반환

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())     # 변수들을 메모리에 생성, 초기화
    for step in range(5001):
        a_, b_, loss_, _ = sess.run([a, b, loss, gradient_descent], feed_dict={X:x_data, Y:y_data})
        if step % 500 == 0:
            print("Epoch: %.f , loss=%.4f,  기울기 a1=%.4f, 기울기 a2=%.4f, 절편 b= %.4f" % (step,  loss_,  a_[0], a_[1],  b_))

Epoch: 0 , loss=3.1340,  기울기 a1=0.6854, 기울기 a2=0.7527, 절편 b= 0.8568
Epoch: 500 , loss=0.2225,  기울기 a1=0.8805, 기울기 a2=-0.5021, 절편 b= -3.2281
Epoch: 1000 , loss=0.1461,  기울기 a1=0.7465, 기울기 a2=0.0389, 절편 b= -5.0851
Epoch: 1500 , loss=0.1080,  기울기 a1=0.5928, 기울기 a2=0.5029, 절편 b= -6.3690
Epoch: 2000 , loss=0.0854,  기울기 a1=0.4686, 기울기 a2=0.8699, 절편 b= -7.3555
Epoch: 2500 , loss=0.0706,  기울기 a1=0.3729, 기울기 a2=1.1619, 절편 b= -8.1580
Epoch: 3000 , loss=0.0602,  기울기 a1=0.2987, 기울기 a2=1.3997, 절편 b= -8.8351
Epoch: 3500 , loss=0.0524,  기울기 a1=0.2398, 기울기 a2=1.5984, 절편 b= -9.4208
Epoch: 4000 , loss=0.0465,  기울기 a1=0.1917, 기울기 a2=1.7683, 절편 b= -9.9368
Epoch: 4500 , loss=0.0417,  기울기 a1=0.1514, 기울기 a2=1.9165, 절편 b= -10.3980
Epoch: 5000 , loss=0.0379,  기울기 a1=0.1169, 기울기 a2=2.0478, 절편 b= -10.8148


In [70]:
#은닉층으로 좌표평면 왜곡, 시그모이드 함수 사용, XOR문제 해결
import tensorflow as tf
import numpy as np

#가중치와 바이어스(편차)
w11 = np.array([-2, -2])
w12 = np.array([2, 2])

w2 = np.array([1, 1])

b1 = 3
b2 = -1
b3 = -1

#perceptron
def MLP(x, w, b):
    y = np.sum(w*x) + b
    if y <=0:
        return 0
    else:
        return 1

#NAND게이트
def NAND(x1, x2):
    return MLP(np.array([x1, x2]), w11, b1)

#OR게이트
def OR(x1, x2):
    return MLP(np.array([x1, x2]), w12, b2)

#AND게이트
def AND(x1, x2):
    return MLP(np.array([x1, x2]), w2, b3)

#XOR게이트
def XOR(x1, x2):
    return AND(NAND(x1, x2), OR(x1, x2))

if __name__ == '__main__':
    for x in [(0, 0), (0, 1), (1, 0), (1, 1)]:
        y = XOR(x[0], x[1])
        print("입력값:"+str(x)+"출력값:"+str(y))

입력값:(0, 0)출력값:0
입력값:(0, 1)출력값:1
입력값:(1, 0)출력값:1
입력값:(1, 1)출력값:0
